using System;
using System.Collections.Generic;

namespace StrategyFramework.Interfaces
{
    /// <summary>
    /// Main interface for a complete modular trading strategy
    /// </summary>
    public interface ISimpleStrategy
    {
        /// <summary>
        /// Name of the strategy configuration
        /// </summary>
        string Name { get; }

        /// <summary>
        /// The entry module for generating buy/sell signals
        /// </summary>
        IEntryModule EntryModule { get; }

        /// <summary>
        /// The exit module for determining when to close positions
        /// </summary>
        IExitModule ExitModule { get; }

        /// <summary>
        /// The position sizing module for determining trade sizes
        /// </summary>
        IPositionSizingModule PositionSizingModule { get; }

        /// <summary>
        /// The risk management module for validating trades
        /// </summary>
        IRiskModule RiskModule { get; }

        /// <summary>
        /// Process market data and execute strategy logic
        /// </summary>
        /// <param name="data">Current market data</param>
        /// <param name="currentPositions">Current portfolio positions</param>
        /// <param name="portfolioValue">Current total portfolio value</param>
        /// <param name="availableCash">Available cash for trading</param>
        /// <returns>List of trade orders to execute</returns>
        List<TradeOrder> ProcessData(SecurityData data, Dictionary<string, decimal> currentPositions, 
                                   decimal portfolioValue, decimal availableCash);
    }

    /// <summary>
    /// Represents a trade order generated by the strategy
    /// </summary>
    public class TradeOrder
    {
        public string Symbol { get; set; }
        public decimal Quantity { get; set; }
        public string OrderType { get; set; } // "Market", "Limit", etc.
        public decimal? LimitPrice { get; set; }
        public string Tag { get; set; }
        public DateTime Timestamp { get; set; }
    }
}